### ISSUE TITLE
Add: Reset data counter (Downloaded/Uploaded)

### ISSUE THREAD

**Issue by lavaplanetmircomposerspirit** [dfaust/plasma-applet-netspeed-widget#25]
Hello when I use netspeed and put the mouse over the widget, a small window appears and shows me the counters for Downloaded and Uploaded.

It would be good if I can also reset the counters during use. 

The solution could be to add a "Reset" button to this window.

**Comment by dfaust** [comment]
The uploaded/downloaded count is tracked by the operating system.
I guess the value of that information is limited anyway. But I don't have any other information to display in the tooltip, so that's why it's there. I'm sorry but I can't see the reason to reset those numbers. They would then differ from the numbers reported by the operating system and would be more confusing.
I guess you are interested in use tracking - as discussed in #20. So I'll close this issue in favor of that one.
